---

- name: nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: delete default server
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  when: nginx_delete_default_server | default(false)
  notify:
    - restart nginx

- name: nginx server
  include: server.yml
  with_items: "{{nginx_servers | default([])}}"

- name: make log directory
  file:
    path: "{{nginx_log_dir}}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755

- name: log rotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644

- name: start service
  service:
    name: nginx
    state: started
    enabled: yes
