---

- set_fact:
    os: centos
    os_release: "{{ansible_distribution_major_version}}"
  when: ansible_distribution == "CentOS"

- set_fact:
    os: centos
    os_release: 6
  when: ansible_distribution == "Amazon"

- name: import key
  rpm_key: key={{nginx_rpm_key_url}}

- name: set up the stable repository
  yum_repository:
    name: nginx
    description: nginx-stable
    baseurl: http://nginx.org/packages/{{os}}/{{os_release}}/$basearch/
    gpgcheck: yes
    enabled: false
  when: nginx_repo_type != 'mainline'

- name: set up the mainline repository
  yum_repository:
    name: nginx
    description: nginx-mainline
    baseurl: http://nginx.org/packages/mainline/{{os}}/{{os_release}}/$basearch/
    gpgcheck: yes
    enabled: false
  when: nginx_repo_type == 'mainline'

- name: install nginx
  yum:
    name: "nginx{{'' if nginx_version is undefined else '-' + nginx_version}}"
    enablerepo: "nginx"
  when: ansible_distribution != "Amazon"

- when: ansible_distribution == "Amazon"
  block:

    - name: install nginx on amazon linux
      yum:
        name: "nginx{{'' if nginx_version is undefined else '-' + nginx_version}}"
        enablerepo: "nginx"
        disablerepo: "amzn-main"


    - name: configure yum update to ignore nginx
      shell: >
        if ! (grep -q '^exclude=' /etc/yum.conf); then
          echo -e "\nexclude=nginx*" >> /etc/yum.conf && echo -e \\nchanged
        elif ! (grep -Eq '^exclude=(.* |)nginx ?' /etc/yum.conf); then
          sed -e 's/^(exclude=.*)$/\1 nginx*/' /etc/yum.conf && echo -e \\nchanged
        fi
      register: result
      changed_when: "'changed' in result.stdout_lines"
